---
debug: true
logging:
#  config: classpath:centralserver-admin-service-test-logback.xml
  level:
    root: INFO
    liquibase: TRACE
    org:
      springframework:
        jdbc:
          core: TRACE
        boot:
          autoconfigure: INFO
        security: DEBUG
        transaction:
          interceptor: DEBUG
      hibernate:
        sql: DEBUG
        type.descriptor: TRACE

#cache:
#  simple:
#    ttl: 5
#
#common-module-endpoints:
#  base-path: /api/v1

spring:
  jpa:
#    open-in-view: false
#    mapping-resources:
#      - apikey.hbm.xml
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: false
#    show-sql: true
#    properties:
#      hibernate:
#        dialect_resolvers: ee.ria.xroad.common.db.Postgres10FixedImplicitSequenceDialectResolver
#        jdbc:
#          time_zone: UTC
#  datasource:
#    # Look org.niis.xroad.centralserver.restapi.config.AbstractFacadeMockingTestContext.ExtDataSourceProperties
#    url-properties:
#      sql.syntax_pgs: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/centerui-changelog.xml
    contexts: test,test

  main:
    lazy-initialization: true

server:
  ssl:
    enabled: false
