# shared properties for dev/prod runtime
# test runtime has a separate application.properties
spring:
  jpa:
    mapping-resources:
      - apikey.hbm.xml
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect_resolvers: ee.ria.xroad.common.db.Postgres10FixedImplicitSequenceDialectResolver
  profiles:
    include: nontest
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    enabled: false
cache:
  simple:
    ttl: 60

common-module-endpoints:
  base-path: /api/v1

server:
  port: 4000
  ssl:
    key-store: /etc/xroad/ssl/internal.p12
    key-store-password: internal
    enabled: true
    ciphers: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg

logging:
  config: file:/etc/xroad/conf.d/centralserver-admin-service-logback.xml
