# shared properties for dev/prod runtime
# test runtime has a separate application.properties
spring:
  servlet:
    multipart.enabled: false
  jackson:
    default-property-inclusion: NON_NULL

server:
  error:
    whitelabel:
      enabled: false
  jetty:
    connection-idle-timeout: 15s
    threads:
      max-queue-capacity: 10000
      max: 32
      acceptors: 2
  servlet:
    jsp:
      registered: false
    session:
      tracking-modes:
  port: 8085
  address: 127.0.0.1
  forward-headers-strategy: native
